import {actionFields,configFields,flagFields,allFields,requiredActionFields,defaultActionType,defaultActionValues,schemaDefault,referenceId,isReturnLocation,weaponGroups,makeConfiguredAction,syncActionTargets,validateActionType} from './action-schema.js';
import {clone,uid,validate,deployedEntities} from './core.js';

export function actionUI({api,getPlan,getCatalog,queryCatalog,showModal,closeModal,modalError,esc,field,button,note,changed,toast}){
  const input=(id,value='',attrs='')=>`<input id="${id}" value="${esc(value)}" ${attrs}>`;
  const catalogState={query:'',page:1,remote:null,loading:'',sequence:0};
  const catalogKey=()=>JSON.stringify([catalogState.query,catalogState.page]);
  async function loadCatalog(key){if(!queryCatalog||catalogState.loading===key||catalogState.remote?.key===key)return;catalogState.loading=key;const sequence=++catalogState.sequence;try{const result=await queryCatalog({query:catalogState.query,page:catalogState.page,pageSize:50});if(sequence!==catalogState.sequence||key!==catalogKey())return;catalogState.remote={key,...result};changed(false);}catch(error){toast(error.message,true);}finally{if(catalogState.loading===key)catalogState.loading='';}}
  function catalogHTML(){
    const query=catalogState.query.trim().toLocaleLowerCase(),local=getCatalog().filter(type=>!query||[type.xdmc,type.rule_type_code].some(value=>String(value).toLocaleLowerCase().includes(query))),localPages=Math.max(1,Math.ceil(local.length/50)),key=catalogKey(),remote=catalogState.remote?.key===key?catalogState.remote:null,visible=remote?remote.items:local.slice((catalogState.page-1)*50,catalogState.page*50),total=remote?.total??local.length,pages=remote?.pages??localPages,page=remote?.page??Math.min(catalogState.page,pages);if(!remote)queueMicrotask(()=>loadCatalog(key));
    return `<div class="panel"><div class="panel-heading"><div><h2>行动类型 · ${getCatalog().length}</h2><p>按名称或代码查找，完整字段在配置页查看。</p></div>${button('添加行动类型','add-action-type','plus','primary')}</div><div class="catalog-toolbar"><div class="searchbox"><input id="action-type-search" type="search" placeholder="搜索行动名称或代码…" aria-label="搜索行动目录" value="${esc(catalogState.query)}"></div></div><div class="panel-body">${note('开始时间和结束时间固定必填。勾选的其它字段在添加行动时必须填写；未勾选的字段不显示，也不输出。策略字段的实际是/否值由每条行动填写。')}${total?`<div class="table-scroll"><table><thead><tr><th>行动名称</th><th>行动代码</th><th>启用字段</th><th>操作</th></tr></thead><tbody>${visible.map(type=>{const enabled=Object.entries(flagFields).filter(([key])=>type[key]);return `<tr><td><b>${esc(type.xdmc)}</b></td><td class="mono">${esc(type.rule_type_code)}</td><td>${enabled.length} 项 <span class="muted field-preview">${enabled.slice(0,4).map(([,schema])=>esc(schema.label)).join('、')}${enabled.length>4?'…':''}</span></td><td>${button('配置字段','edit-action-type','edit','small',`data-id="${esc(type.rule_type_code)}"`)}</td></tr>`;}).join('')}</tbody></table></div><div class="catalog-pager"><span>共 ${total} 条 · 第 ${page} / ${pages} 页</span><div class="row"><button class="button small" data-act="action-type-page" data-value="${page-1}" ${page<=1?'disabled':''}>上一页</button><button class="button small" data-act="action-type-page" data-value="${page+1}" ${page>=pages?'disabled':''}>下一页</button></div></div>`:'<div class="empty compact"><h3>没有匹配的行动类型</h3><p>调整搜索条件后重试。</p></div>'}</div></div>`;
  }
  function setCatalogQuery(value){catalogState.query=value;catalogState.page=1;}
  function setCatalogPage(value){catalogState.page=Number(value)||1;}
  function typeDialog(code){
    const existing=getCatalog().find(t=>t.rule_type_code===code),type=clone(existing||{...defaultActionType,rule_type_code:'',xdmc:''});
    const section=(title,fields)=>`<section class="command-section"><h3>${title}</h3><div class="choice-grid">${Object.entries(fields).filter(([key])=>key in flagFields).map(([key,schema])=>`<label class="choice"><input type="checkbox" data-type-flag="${key}" ${type[key]?'checked':''}><span>${esc(schema.label)}<small>${key}</small></span></label>`).join('')}</div></section>`;
    showModal(existing?'配置行动字段':'添加行动类型','一条记录定义一种行动，以及该行动需要填写的项目。',`<form id="action-type-form"><div class="form-grid">${field('行动代码',input('type-code',type.rule_type_code,`required pattern="[0-9]{6}" placeholder="六位数字" ${existing?'readonly':''}`))}${field('行动名称',input('type-name',type.xdmc,'required'))}</div>${section('行动字段',actionFields)}${section('策略字段',configFields)}${note('开始时间和结束时间固定必填，无需配置。行动编号启用后由系统为每条行动独立生成。修改类型配置只影响新建行动；已有行动保留创建时的字段配置。')}</form>`,button('取消','close')+'<button class="button primary" form="action-type-form">保存行动类型</button>',true);
    document.querySelector('#action-type-form').onsubmit=async event=>{event.preventDefault();const value={rule_type_code:document.querySelector('#type-code').value.trim(),xdmc:document.querySelector('#type-name').value.trim(),...Object.fromEntries([...document.querySelectorAll('[data-type-flag]')].map(el=>[el.dataset.typeFlag,el.checked]))};const errors=validateActionType(value);if(errors.length)return modalError(errors[0]);const submit=document.querySelector('[form="action-type-form"]');submit.disabled=true;try{await api.saveActionType(value,!!existing);catalogState.remote=null;closeModal();changed(false);toast('行动类型已保存到数据库。');}catch(e){modalError(e.message);submit.disabled=false;}};
  }
  function dialog(id=null,presetOwners=[]){
    const plan=getPlan(),roots=deployedEntities(plan),existing=plan.actions.find(a=>a.id===id),types=clone(getCatalog());
    if(!roots.length)return toast('请先在地图添加执行实体。',true);
    if(!types.length)return toast('请先在模型与行动页面添加行动类型。',true);
    let definition=clone(existing?.definition||types.find(t=>t.rule_type_code===existing?.code)||types[0]);
    const validPreset=presetOwners.filter(id=>roots.some(entity=>entity.id===id));let owners=existing?[existing.executor]:(validPreset.length?validPreset:[roots[0].id]),values=existing?.values?clone(existing.values):defaultActionValues(plan,owners[0]);
    if(existing&&!existing.definition){
      definition.launch=!!existing.weapon;definition.route=!!existing.route?.length;
      values.start_time=existing.start;values.end_time=existing.end;
      values.target=existing.targets.map(id=>({target_id:referenceId(roots.find(e=>e.id===id))}));
      if(existing.weapon){values.launch[0].weapon_type=weaponGroups(plan,existing.executor).find(w=>w.mount_type===existing.weaponModelId)?.mount_type||existing.weaponModelId;values.launch[0].weapon_num=existing.count;}
      if(existing.route?.length)values.route=[{points:existing.route.map((point,order)=>({...point,order}))}];
    }
    if(existing){const index=types.findIndex(t=>t.rule_type_code===definition.rule_type_code);if(index>=0)types[index]=definition;else types.push(definition);}
    let typeQuery='',ownerQuery='',ownerSide='all',ownerPage=1;const refQueries=new Map();
    const typeOptions=items=>items.map(t=>`<option value="${esc(t.rule_type_code)}" ${definition.rule_type_code===t.rule_type_code?'selected':''}>${esc(t.xdmc)}（${esc(t.rule_type_code)}）</option>`).join('');
    showModal(existing?'编辑行动':'添加行动','先确定执行实体与时间，再填写当前类型启用的行动参数。',`<form id="command-form"><div class="form-grid command-basics">${field('搜索行动类型',input('command-type-search','',`${existing?'disabled ':''}type="search" placeholder="输入名称或代码"`))}${field('行动类型',`<select id="command-type" ${existing?'disabled':''}>${typeOptions(types)}</select>`)}${field('每个实体的行动条数',input('command-repeat',1,`type="number" min="1" max="50" step="1" required ${existing?'disabled':''}`),'单次最多生成 1000 条行动。','full')}</div><details class="owner-picker-disclosure"><summary><span>执行实体 <b id="owner-count"></b></span><small>点击更改或批量选择</small></summary><div class="owner-picker"><div class="owner-picker-tools"><input id="command-owner-search" type="search" placeholder="搜索实体名称或装备" aria-label="搜索执行实体" ${existing?'disabled':''}><select id="command-owner-side" aria-label="筛选执行实体阵营" ${existing?'disabled':''}><option value="all">全部阵营</option><option value="Blue">蓝方</option><option value="Red">红方</option></select><button type="button" class="button small" id="select-filtered-owners" ${existing?'disabled':''}>选择全部筛选结果</button></div><div class="owner-picker-grid"><div><div class="picker-title">可选实体</div><div id="command-owners" class="owner-results"></div><div id="owner-pager" class="owner-pager"></div></div><div><div class="picker-title">已选实体</div><div id="selected-owners" class="selected-owners"></div></div></div></div></details><section class="command-required"><div class="command-required-title"><b>行动时间</b><span>固定必填 · 相对仿真开始时间</span></div><div id="command-time-fields" class="form-grid"></div><p id="command-time-summary" class="command-time-summary"></p></section><p id="command-batch-summary" class="note"></p><div id="command-fields"></div></form>`,button('取消','close')+'<button class="button primary" form="command-form">应用到方案</button>','drawer');
    const form=document.querySelector('#command-form'),fields=document.querySelector('#command-fields'),timeFields=document.querySelector('#command-time-fields');
    const pathString=path=>esc(JSON.stringify(path));
    function choices(ref){const owner=roots.find(e=>e.id===owners[0]);if(!owner)return [];if(ref==='executor')return [{value:referenceId(owner),label:owner.name}];if(ref==='weapon')return weaponGroups(plan,owner.id).map(w=>({value:w.mount_type,label:`${w.mount_type_name} · ${w.num} 个`}));return roots.filter(e=>ref==='target'?e.side!==owner.side:ref==='airport'?isReturnLocation(e,owner.side):true).map(e=>({value:referenceId(e),label:e.name}));}
    function control(schema,value,path){
      const token=pathString(path),key=path.join('.');
      if(schema.type==='object')return `<fieldset class="command-section"><legend>${esc(schema.label)}</legend><div class="form-grid">${Object.entries(schema.properties).map(([k,s])=>control(s,value?.[k],[...path,k])).join('')}</div></fieldset>`;
      if(schema.type==='array')return `<fieldset class="command-section full"><legend>${esc(schema.label)}${schema.optional?'（可选）':''}</legend>${schema.optional?'<p class="small muted">不配置时可删除全部条目，生成指令时将省略此项。</p>':''}${(value||[]).map((item,index)=>`<div class="command-array-row"><div class="grow">${control(schema.item,item,[...path,index])}</div><button type="button" class="button small" data-array-remove="${token}" data-index="${index}" ${(value||[]).length<=schema.min?'disabled':''}>删除条目</button></div>`).join('')}<button type="button" class="button small" data-array-add="${token}" ${(value||[]).length>=(schema.max??500)?'disabled':''}>添加${esc(schema.item.label)}</button></fieldset>`;
      if(schema.generated)return field(schema.label,'<input value="'+esc(existing?.id||'保存后自动生成，每条行动唯一')+'" readonly>','','full');
      let html;
      const attrs=`data-command-path="${token}" aria-label="${esc(key)}"`;
      if(schema.type==='boolean')html=`<select ${attrs}><option value="true" ${value===true?'selected':''}>是</option><option value="false" ${value===false?'selected':''}>否</option></select>`;
      else if(schema.ref){const options=choices(schema.ref),query=refQueries.get(key)||'',matches=options.filter(option=>!query||[option.label,option.value].some(text=>String(text).toLocaleLowerCase().includes(query.toLocaleLowerCase()))),selected=options.find(option=>option.value===value),visible=[...new Map([...(selected?[selected]:[]),...matches].map(option=>[option.value,option])).values()].slice(0,100),search=schema.ref==='executor'?'':`<input type="search" data-ref-search="${token}" value="${esc(query)}" placeholder="搜索${esc(schema.label)}" aria-label="搜索${esc(schema.label)}">`;html=`<div class="reference-picker">${search}<select ${attrs} ${schema.empty?'':'required'} ${schema.ref==='executor'?'disabled':''}><option value="">${schema.empty?'不设置':'请选择'}</option>${visible.map(x=>`<option value="${esc(x.value)}" ${x.value===value?'selected':''}>${esc(x.label)}</option>`).join('')}${value&&!options.some(x=>x.value===value)?`<option value="${esc(value)}" selected>引用已失效，请重新选择</option>`:''}</select>${options.length>100?`<small>匹配 ${matches.length} 条，最多显示前 100 条。</small>`:''}</div>`;}
      else html=`<input ${attrs} type="${schema.type==='number'?'number':'text'}" value="${esc(value??'')}" ${schema.empty?'':'required'} ${schema.type==='number'?`step="${schema.integer?1:'any'}" ${schema.min!=null?`min="${schema.min}"`:''} ${schema.max!=null?`max="${schema.max}"`:''}`:''}>`;
      return field(schema.label,html);
    }
    function get(path){return path.reduce((v,key)=>v[key],values);}
    function set(path,value){const parent=path.slice(0,-1).reduce((v,key)=>v[key],values);parent[path.at(-1)]=value;}
    function schemaAt(path){let schema=allFields[path[0]];for(const key of path.slice(1))schema=schema.type==='array'?schema.item:schema.properties[key];return schema;}
    function timeSummary(){const start=Number(values.start_time),end=Number(values.end_time),base=new Date(plan.start.replace(' ','T')),clock=value=>{if(!Number.isFinite(value)||Number.isNaN(base.getTime()))return '—';const date=new Date(base.getTime()+value*1000);return date.toLocaleTimeString('zh-CN',{hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'});};const node=document.querySelector('#command-time-summary');if(node)node.textContent=`${clock(start)} — ${clock(end)} · 时长 ${Number.isFinite(start)&&Number.isFinite(end)&&end>=start?`${end-start} 秒`:'待校验'}`;}
    function summary(){document.querySelector('#command-batch-summary').textContent=`${owners.length} 个执行实体 × ${document.querySelector('#command-repeat').value||0} 条行动，将应用 ${owners.length*Number(document.querySelector('#command-repeat').value||0)} 个独立编号。`;}
    const compatible=entity=>!owners.length||(()=>{const first=roots.find(item=>item.id===owners[0]);return entity.side===first.side&&entity.model.mxlx===first.model.mxlx;})();
    function ownerMatches(entity){return (ownerSide==='all'||entity.side===ownerSide)&&(!ownerQuery||[entity.name,entity.model.mxmc].some(value=>value.toLocaleLowerCase().includes(ownerQuery.toLocaleLowerCase())));}
    function drawOwners(){
      const matches=roots.filter(ownerMatches),pages=Math.max(1,Math.ceil(matches.length/50));ownerPage=Math.min(ownerPage,pages);const visible=matches.slice((ownerPage-1)*50,ownerPage*50);
      document.querySelector('#command-owners').innerHTML=visible.map(entity=>`<label class="owner-option ${compatible(entity)?'':'incompatible'}"><input type="checkbox" name="command-owner" value="${entity.id}" ${owners.includes(entity.id)?'checked':''} ${existing||!compatible(entity)?'disabled':''}><span><b>${esc(entity.name)}</b><small>${entity.side==='Blue'?'蓝方':'红方'} · ${esc(entity.model.mxmc)}</small></span></label>`).join('')||'<p class="small muted">没有匹配的执行实体。</p>';
      document.querySelector('#selected-owners').innerHTML=owners.map(id=>{const entity=roots.find(item=>item.id===id);return entity?`<span class="selected-token">${esc(entity.name)}${existing?'':`<button type="button" data-remove-owner="${entity.id}" aria-label="移除 ${esc(entity.name)}">×</button>`}</span>`:'';}).join('')||'<p class="small muted">尚未选择实体。</p>';
      document.querySelector('#owner-count').textContent=`${owners.length} 个`;
      document.querySelector('#owner-pager').innerHTML=`<button type="button" data-owner-page="${ownerPage-1}" ${ownerPage<=1?'disabled':''}>上一页</button><span>${ownerPage} / ${pages}</span><button type="button" data-owner-page="${ownerPage+1}" ${ownerPage>=pages?'disabled':''}>下一页</button>`;summary();
    }
    function draw(){const open=new Set([...fields.querySelectorAll('.command-form-group[open]')].map(node=>node.dataset.group)),scroll=document.querySelector('.modal-body')?.scrollTop||0,first=!fields.childElementCount;timeFields.innerHTML=Object.entries(requiredActionFields).map(([key,schema])=>control(schema,values[key],[key])).join('');fields.innerHTML=[['params','行动参数',Object.fromEntries(Object.entries(actionFields).filter(([key])=>!(key in requiredActionFields)))],['strategy','行为策略',configFields]].map(([group,title,schemas],index)=>`<details class="command-form-group" data-group="${group}" ${open.has(group)||first&&index===0?'open':''}><summary><span>${title}</span><small>${Object.entries(schemas).filter(([key])=>definition[key]).length} 项</small></summary><div class="form-grid">${Object.entries(schemas).filter(([key])=>definition[key]).map(([key,schema])=>control(schema,values[key],[key])).join('')||'<p class="muted">此类型未启用相关字段。</p>'}</div></details>`).join('');if(document.querySelector('.modal-body'))document.querySelector('.modal-body').scrollTop=scroll;summary();timeSummary();}
    form.oninput=event=>{const el=event.target;if(el.dataset.refSearch){const path=JSON.parse(el.dataset.refSearch),key=path.join('.'),cursor=el.selectionStart;refQueries.set(key,el.value);draw();const next=[...fields.querySelectorAll('[data-ref-search]')].find(input=>input.dataset.refSearch===el.dataset.refSearch);next?.focus();next?.setSelectionRange(cursor,cursor);return;}if(!el.dataset.commandPath)return;const path=JSON.parse(el.dataset.commandPath),schema=schemaAt(path);set(path,schema.type==='number'?(el.value===''?null:Number(el.value)):schema.type==='boolean'?el.value==='true':el.value);if(path[0]==='start_time'||path[0]==='end_time')timeSummary();};
    form.onchange=form.oninput;
    fields.onclick=event=>{const el=event.target.closest('[data-array-add],[data-array-remove]');if(!el)return;const adding=el.dataset.arrayAdd!=null,path=JSON.parse(adding?el.dataset.arrayAdd:el.dataset.arrayRemove),items=get(path)||[],schema=schemaAt(path);if(adding){if(items.length>=(schema.max??500))return;const item=schemaDefault(schema.item);if(item&&typeof item==='object'&&'order' in item)item.order=items.length;items.push(item);set(path,items);}else{if(items.length<=schema.min)return;items.splice(Number(el.dataset.index),1);}draw();};
    const typeSelect=document.querySelector('#command-type');
    document.querySelector('#command-type-search').oninput=event=>{typeQuery=event.target.value;const matches=types.filter(type=>!typeQuery||type.xdmc.toLocaleLowerCase().includes(typeQuery.toLocaleLowerCase())||type.rule_type_code.includes(typeQuery));typeSelect.innerHTML=matches.length?typeOptions(matches):'<option value="">没有匹配的行动类型</option>';typeSelect.disabled=!matches.length;document.querySelector('[form="command-form"]').disabled=!matches.length;if(matches.length&&!matches.some(type=>type.rule_type_code===definition.rule_type_code)){definition=clone(matches[0]);values=defaultActionValues(plan,owners[0]||roots[0].id);draw();}};
    typeSelect.onchange=event=>{definition=clone(types.find(t=>t.rule_type_code===event.target.value));values=defaultActionValues(plan,owners[0]||roots[0].id);draw();};
    document.querySelector('#command-owner-search').oninput=event=>{ownerQuery=event.target.value;ownerPage=1;drawOwners();};
    document.querySelector('#command-owner-side').onchange=event=>{ownerSide=event.target.value;ownerPage=1;drawOwners();};
    document.querySelector('#command-owners').onchange=event=>{const id=event.target.value;if(event.target.checked&&!owners.includes(id))owners.push(id);else if(!event.target.checked)owners=owners.filter(owner=>owner!==id);if(owners.length){const defaults=defaultActionValues(plan,owners[0]);values.executor=defaults.executor;values.target=defaults.target;values.launch=defaults.launch;values.radar_detect_mode=defaults.radar_detect_mode;}drawOwners();draw();};
    document.querySelector('.owner-picker').onclick=event=>{const remove=event.target.closest('[data-remove-owner]'),pageButton=event.target.closest('[data-owner-page]');if(remove){owners=owners.filter(id=>id!==remove.dataset.removeOwner);drawOwners();draw();}else if(pageButton){ownerPage=Number(pageButton.dataset.ownerPage);drawOwners();}};
    document.querySelector('#select-filtered-owners').onclick=()=>{const matches=roots.filter(ownerMatches);if(!matches.length)return;let first=roots.find(entity=>entity.id===owners[0]);if(!first||!matches.some(entity=>entity.side===first.side&&entity.model.mxlx===first.model.mxlx)){first=matches[0];owners=[];}owners=[...new Set([...owners,...matches.filter(entity=>entity.side===first.side&&entity.model.mxlx===first.model.mxlx).map(entity=>entity.id)])];const defaults=defaultActionValues(plan,owners[0]);values.executor=defaults.executor;values.target=defaults.target;values.launch=defaults.launch;values.radar_detect_mode=defaults.radar_detect_mode;drawOwners();draw();};
    document.querySelector('#command-repeat').oninput=summary;
    document.querySelector('#command-form').onsubmit=event=>{
      event.preventDefault();const repeat=Number(document.querySelector('#command-repeat').value);
      if(!owners.length)return modalError('请选择至少一个执行实体。');
      if(!Number.isSafeInteger(repeat)||repeat<1||repeat>50)return modalError('每个实体的行动条数必须是 1–50 的整数。');
      if(owners.length*repeat>1000)return modalError('单次最多创建 1000 条行动，请减少执行实体或行动条数。');
      const first=roots.find(e=>e.id===owners[0]);if(owners.some(id=>{const e=roots.find(e=>e.id===id);return e.side!==first.side||e.model.mxlx!==first.model.mxlx;}))return modalError('批量创建请选择同一阵营、同一型号的实体。');
      const added=owners.flatMap(owner=>Array.from({length:repeat},()=>{
        const current=clone(values),e=roots.find(e=>e.id===owner);
        if(current.executor?.length){current.executor[0].executor_id=referenceId(e);current.executor[0].formation_struct?.forEach(part=>{if(part.formation_id===first.formationId)part.formation_id=e.formationId;});}
        return syncActionTargets(makeConfiguredAction(definition,current,owner,existing?.id||uid('ACT_')),plan);
      }));
      const candidate={...plan,actions:[...plan.actions.filter(a=>a.id!==existing?.id),...added]};
      const originalErrors=new Set(validate({...plan,actions:plan.actions.filter(a=>a.id!==existing?.id)}).errors.map(e=>e.message));
      const errors=validate(candidate).errors.filter(e=>!originalErrors.has(e.message)||owners.some(owner=>e.message.startsWith(roots.find(x=>x.id===owner).name+'：')));
      if(errors.length)return modalError(errors[0].message);
      if(existing)plan.actions[plan.actions.indexOf(existing)]=added[0];else plan.actions.push(...added);
      closeModal();changed(true);toast(`已将 ${added.length} 条行动应用到方案，请保存方案。`);
    };
    drawOwners();draw();
  }
  return {catalogHTML,typeDialog,dialog,setCatalogQuery,setCatalogPage};
}
